//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRestWT.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public int CodSeguimiento { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string NIT { get; set; }
        public string IMEI { get; set; }
        public string NroPlaca { get; set; }
        public string UsuaReg { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string UsuaModif { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
